### ISSUE TITLE
Found Error on crawl_cat_list.py

### ISSUE THREAD

**Issue by abahkool** [lthoangg/shopee-crawler#12]
**Python version: 3.10.4
PIP version: 22.1
OS: Windows 11 22000.675**
=============================
Found problem if origin other then shopee.vn:
Example:
shopee.co.id
shopee.com.my
shopee.sg

Code:
```
import time
from shopee_crawler import Crawler`

crawler = Crawler()
crawler.set_origin(origin="shopee.co.id")

keyword = 'Beauty'
start = time.time()
data = crawler.crawl_by_search(keyword=keyword)
data = crawler.crawl_cat_list()
end = time.time()

print("Time : ",end - start, "seconds")

```

Error:
```
INFO:shopee_crawler.toolkit.crawl_by_search:There are 6516 products in "Beauty"
Traceback (most recent call last):
  File "D:\Program Files\Python310\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(  File "D:\Program Files\Python310\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\Program Files\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\Program Files\Python310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "D:\Program Files\Python310\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "D:\Program Files\Python310\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "D:\Program Files\Python310\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001E33565F070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python310\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "D:\Program Files\Python310\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "D:\Program Files\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='banhang.shopee.co.id', port=443): Max retries exceeded with url: /help/api/v3/global_category/list/?page=1&size=16 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E33565F070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\shopee-crawler\index.py", line 14, in <module>
    data = crawler.crawl_cat_list()
  File "D:\Program Files\Python310\lib\site-packages\shopee_crawler\crawler.py", line 31, in crawl_cat_list
    return crawl_cat_list(self.origin)
  File "D:\Program Files\Python310\lib\site-packages\shopee_crawler\toolkit\crawl_cat_list.py", line 28, in crawl_cat_list
    total_count = get_total(origin)
  File "D:\Program Files\Python310\lib\site-packages\shopee_crawler\toolkit\crawl_cat_list.py", line 12, in get_total
    return curl(url)['data']['total']
  File "D:\Program Files\Python310\lib\site-packages\shopee_crawler\toolkit\curl.py", line 17, in wrapper
    return func(url)
  File "D:\Program Files\Python310\lib\site-packages\shopee_crawler\toolkit\curl.py", line 32, in curl
    return requests.get(
  File "D:\Program Files\Python310\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "D:\Program Files\Python310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Program Files\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Program Files\Python310\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "D:\Program Files\Python310\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='banhang.shopee.co.id', port=443): Max retries exceeded with url: /help/api/v3/global_category/list/?page=1&size=16 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E33565F070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

**Comment by lthoangg** [comment]
bug is now fixed on version 0.2.2.
Please re-install and try again.

!pip install shopee-crawler==0.2.2
